### ISSUE TITLE
Space padding in a delimited field reported as an error

### ISSUE THREAD

**Issue by jacobcontreras** [NASA-PDS-Incubator/validate#1024]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

A data file is both fixed width and delimited so that the data contains space padding. The metadata in this file has blank spaces for known missing data values. Instead of interpreting the spaces as null values it is interpreting a data type error. 

### 🕵️ Expected behavior

The expected behavior is that it should treat the space padding as a null value. 

### 📜 To Reproduce

1. Run validate on these products
[OCCLOGM4.zip](https://github.com/user-attachments/files/17296772/OCCLOGM4.zip)

### 🖥 Environment Info

- Version of this software = 3.5.2

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@jacobcontreras per the description of the PDS4 Delimited table standard in the PDS4 Standards Reference, all characters (including whitespace characters) within a delimited table field are considered a part of the field value. Fixed width tables do allow space padding.

<img width="625" alt="Screenshot 2024-10-08 at 2 18 45 PM" src="https://github.com/user-attachments/assets/378b8868-7096-482c-aa23-86a7b1fb6d4f">

**Comment by jacobcontreras** [comment]
1,  100,16,20260, 15601, 53.9,  0.00,
1,  100,16,     ,      ,     ,      ,
1,  100,16,20260, 15601, 52.9,  0.00,
Here is an excerpt where the padding is being interpreted as an error. The value "100" contains 2 byte padding which is properly recognized as part of the field but not the value, whereas the blank spaces are what is causing the error in the validate tool.

**Comment by jmafi** [comment]
Unfortunately the extra spaces were eliminated in @jacobcontreras post. The excerpt with the spaces preserved is as follows:

```1,  100,16,20260, 15601, 53.9,
1,  100,16,     ,      ,     ,
1,  100,16,20260, 15601, 52.9,
1,  100,16,     ,      ,     ,
```
In the second field shown in the excerpt, Validate correctly interprets the field value as an integer (100) and treats the two spaces preceding the data value as space padding. In the case of the fields 4-6, however, Validate is treating the spaces as text rather than treating the spaces a padding and the field as null. 

The DSV spec is somewhat vague on the distinction between field length and value. I believe that the text that @jordanpadams cited refers specifically to field length. I don't recall why that detail would be of interest, other than possibly for determining the correct attribute value for maximum_field_length. I believe that the implication of the DSV spec is that, unlike the field length, when interpreting the data value, leading or trailing spaces which are not enclosed in quotes should be ignored. This is inferred both by the last sentence in paragraph 5 that @jordanpadams posted, and the following paragraph (see highlighted text below).

![sr-4c-pg27](https://github.com/user-attachments/assets/5794d558-894b-4c6b-9143-20d9411812b5)

In cases as in the data excerpt above, where a field consists of only spaces which have not been quoted, Validate should treat those spaces a leading spaces and the values should be treated as null, the same as it would be two adjacent delimiters (e.g. \",,\").

**Comment by jordanpadams** [comment]
@jmafi Unfortunately this is yet another issue where we have changed the software >5 times and spent dozens of hours flip-flopping on different solutions due to lack of clarity in the standard. Please bring this to the CCB to clarify the SR and create a new requirement (vs a bug) to reflect a new clear requirement on the validation software. Thanks.

**Comment by jordanpadams** [comment]
@jacobcontreras ☝️
