### ISSUE TITLE
As a user, I want to validate all internal references to products in the PDS archive are valid

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#415]
## 💪 Motivation
...so that I can ensure all collections referenced by bundles, all products referenced by collections, and all products referenced by other products are valid.

## 📖 Additional Details

See child stories for more granular requirements and acceptance criteria.

## ⚙️ Engineering Details

NOTE: This requirement is mostly implemented by validate already, but checking ALL references will require the registry.

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

Do you want this to just do bundles or any type of product? If the latter, which makes more sense, then should be:

```
--registry-login username:password
--registry-url https://localhost:8080
```

These two arguments allow any product not just bundles to be validated and it prevents an explosion of `--observational-lidvid`, `--documentation-lidvid`, etc. Also saves having to show that the lidvid is really a bundle, obs, doc, etc.

It will require each argument be checked to see if it is a file or lid/lidvid. Do all lids start with urn: while files never do? Makes a fast check but it is not the only way to do it.

**Comment by jordanpadams** [comment]
@al-niessner +1 to this working for any type of product, not just bundles. 

that being said, I am thinking it may make sense for us to implement an auth layer for the API to access `staged` data, vs. trying to access to the Registry directly. The former will be necessary eventually, so it seems like implementing for the Registry now would just be a waste since we will eventually want to use the API to do this.

the other option is, we skip the auth part altogether for now, and assume the data is all publicly accessible through the API?

thoughts?

@tloubrieu-jpl @jimmie ☝️

**Comment by al-niessner** [comment]
@jordanpadams @jimmie @tloubrieu-jpl 

I was going to implement without auth but leave the hook there. How it is implemented should not matter to staged or otherwise. auth just gives more access.

**Comment by jordanpadams** [comment]
@al-niessner +1 perfect. let's change that to `api-login` and `api-url` then.

**Comment by al-niessner** [comment]
@jimmie @jordanpadams @tloubrieu-jpl 

Added api-login and api-url easy enough. Say a lidvid is given like 'urn:nasa:pds:insight_seis:data_table:stationxml.xb.elyhk.2019.245::1.1'. Do we download it to a file locally then process it? Do we download it later when the file is read but it looks like a file for validation may be read more than once. Accessing registry-api more than may be more of a performance burden than reading a file. Downloading lidvids will require disk storage though. Potentially lots of disk storage.

**Comment by al-niessner** [comment]
@jimmie @jordanpadams @tloubrieu-jpl 

Digging further in, it may be possible and least of a disturbance to use a single file for lidvids. It would be done near ValidationLauncher before file validation begins. It seems a good middle ground.

**Comment by jordanpadams** [comment]
@al-niessner for referential integrity, we only need to go one level deep. So if a product references product X, we just need to go out to the registry and check that product X actually exists.

Note: for products in the same collection/bundle, they may have not been registered yet. So we will also need to check within the current validation run if those LID/LIDVIDs exist.

**Comment by jordanpadams** [comment]
In other words, thks integrity check should never require downloading of data.

**Comment by al-niessner** [comment]
@jordanpadams 

Oh, I read it as a lidvid on the command line, look it up, then check that its references were valid.  Will do reference checks using registry if available.

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life  @tloubrieu-jpl 

How robust does this check need to be? Lets say the user uses a bundle lidvid. Can use the registry-api to get the ref_lid_collection and ref_lid_collection_secondary for the collections the bundle contains. Unfortunately for the products a collection contains, it requires values in the registry-refs not the registry and registry-api does not give direct access to this content. Therefore, do we need/want robust testing where the tool can independently look up the product lidvids contained within a collection or trust/rely-upon the registry-api to correct convert the /products/{collection lidvid}/members? In the former, robust choice, direct access to opensearch will be needed. In the latter, rely on registry-api, we will foist some of the tool requirements onto the registry-api which may not align with user desires. I am currently leaning toward direct opensearch access as best approach because it is most robust and keeps requirements local to the tool, which I think out weighs using already developed code (registry-api) albeit for a different use. Your choice and why? 

More:

Turns out there is a further validation of references that you may want to do as well. There are ref_lid_* that should be verified against what is contain in registry-refs. Goes back to using opensearch instead of registry-api.

**Comment by jordanpadams** [comment]
@al-niessner it must be as robust as possible. this checks the integrity of the system, so if we miss something, then bad data can get into the system.

> do we need/want robust testing where the tool can independently look up the product lidvids contained within a collection or trust/rely-upon the registry-api to correct convert the /products/{collection lidvid}/members

we need to trust in the registry-api. if we can't ensure the accuracy of our registry-api through our testing, then our testing needs to change because otherwise there is no point in having the registry-api altogether. :-)

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @nutjob4life ☝️

**Comment by al-niessner** [comment]
> @al-niessner it must be as robust as possible. this checks the integrity of the system, so if we miss something, then bad data can get into the system.
> 
> > do we need/want robust testing where the tool can independently look up the product lidvids contained within a collection or trust/rely-upon the registry-api to correct convert the /products/{collection lidvid}/members
> 
> we need to trust in the registry-api. if we can't ensure the accuracy of our registry-api through our testing, then our testing needs to change because otherwise there is no point in having the registry-api altogether. :-)

@jordanpadams

Sorry, but your response is contradictory and I cannot tell what you really think is important. One, we can validate the database without registry-api (my recommendation) and it would be the most robust way to validate the contents of the database.

Using the registry-api to validate the database relies on the registry-api to be correct. If it is not, then you end up with bad data in the database which is what you are trying to avoid.

However, you want to use the registry-api because it also needs to be right.

Therefore, are you saying:

* test the database independently (without registry-api) then test again with registry-api to show that the database is correct and that registry-api is functioning properly?

OR

* trust that the registry-api is correct then when problems are found, discuss the problem in a haze since the problem can be in the database or registry-api?

**Comment by al-niessner** [comment]
@jordanpadams 

You wrote:
> we need to trust in the registry-api. if we can't ensure the accuracy of our registry-api through our testing, then our testing needs to change because otherwise there is no point in having the registry-api altogether. :-)

Does that imply they only purpose of the registry-api is for validate to do integrity referencing? I thought the purpose of the registry-api was to support users needs not validate's needs. In fact, registry-api does not support validate needs at all for reference integrity checking but can be twisted to do so in a painful way.

**Comment by jordanpadams** [comment]
@al-niessner FYI, you probably saw this come through, but I broke this up into several lower level requirements to ensure we cover all our bases and have sufficient tests written to meet the various acceptance criteria. Let me know if you think I missed anything.

**Comment by jordanpadams** [comment]
@al-niessner began work on internal references

**Comment by tloubrieu-jpl** [comment]
@al-niessner is looking to find a concise way of doing http request with user/password.

**Comment by nutjob4life** [comment]
Something like this? https://stackoverflow.com/a/3283496/693085

**Comment by miguelp1986** [comment]
@al-niessner can you please provide test cases for us to test?

**Comment by tloubrieu-jpl** [comment]
@miguelp1986 you should look at the acceptance criteria described in the child tickets for test cases. You don't need to specifically test that ticket (unless you think of specific cases) if you tested the sub-tickets according to the acceptance criteria described there.

The sub tickets are listed in the table above (#316, #595, #596)
