### ISSUE TITLE
Refactor regex handling to use Google's RE2J library and compile

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#520]
## 💪 Motivation
Per https://github.com/NASA-PDS/validate/security/code-scanning/8, our software could be significantly more efficient using the Google library instead of standard Java libraries.

Additionally, per comments from @al-niessner, we should be compiling the regex prior to checking for a match to improve performance. Not sure if that is still the case if we switch to Google's regex library.

## ⚖️ Acceptance Criteria
The short answer: regression tests all pass

Some more specific criteria examples:

**Given** some valid PDS4 bundle
**When I perform** validation
**Then I expect** the bundle to pass as expected, ensuring it crawls through and validating all files as expected (the regex is used to find all XML files in the bundle)

**Given** and invalid PDS4 bundle with at least 1 invalid LID/LIDVID
**When I perform** validation
**Then I expect** that bundle to fail indicating an invalid LID/LIDVID

**Comment by al-niessner** [comment]
Standard library Pattern.matches() - 10.2 seconds for 1 million checks
Standard library Pattern.compile() .Matcher().matches() - 1.6 seconds for 1 million checks

Google RE2J Pattern.compile().Matcher().matches - 5.4 seconds for 1 million checks.


Staying with standard library since it is 4x faster.

**Comment by jordanpadams** [comment]
@al-niessner copy that. closing as wontfix
