### ISSUE TITLE
Add unit tests to support registry referential integrity checker tool

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#603]
## 💡 Description

We should have some sort of tests included with the new referential integrity checker tool. Since the software depends on the registry and integration tests cannot be easily developed within this repo, we should have some sort of units tests in place.

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

Still cannot find a good solution to this problem. There are 4 elements to the reference integrity checker:

1. CLI
2. threading
3. reference exists or missing report
4. get data from source

The first part (CLI) is not super testable in a unit test sense. Can test the parsing but that is  a third party library not home grown.

The second part (threading) is pretty straight forward and uses built in synchronized. Not sure what is there to be tested. It is a direct implementation of the general making it impossible to test stand alone. In other words, it directly creates the runnable object and starts is execution. The loops that does this is the test interesting part but the loop cannot be executed without fetching lidvids and thus a connection to opensearch.

Third part (reference test) is really a simply yeah or neah from opensearch in if it found it or not. Once the lidvid is found via opensearch, the flag is set. It is really hard to break up an if statement to make it testable. Processing references of a lidvid is equally as trivial as they come in a list from opensearch so one is testing a for statement because the content of the for loop is trivial. I mean this is all of the code we are talking about:

```
      if (search.exists(this.lidvid)) {
        this.log.info("The lidvid '" + this.lidvid + "' is of type: " + search.getProductTypeOf(this.lidvid));
        for (String reference : search.getReferencesOf(this.lidvid)) {
          if (search.exists(reference)) referenced_valid_lidvids.add(reference);
          else {
            this.broken++;
            this.reporter.error ("In the search the lidvid '" + this.lidvid + "' references '" + reference + "' that is missing in the database.");
          }
        }
      } else this.reporter.error("The given lidvid '" + this.lidvid + "' is missing from the database.");
```

Fourth part (get data from source) is the interesting part because it does all of the work. It has to find the item. Download it. Return enough of the document to continue processing. In fact, all of the interesting functions of `search.*` are direct access to opensearch.

The real test is to simply run it against some opensearch database. In fact, that is what I have begun installing to where the test code returns the SearchResponse that a call to opensearch would generate. In essence, emulate opensearch. However, opensearch is not accommodating in any way. I can do a search (with curl), save it in a file, then load it again instead of having a live db -- looks like it may work but I have not tested it. The tool can be then tested in whole where part 4 is emulation so that we can see that the CLI, threads, and if statement is working.

The question goes back out to y'all, is this really what you had in mind? If not, then what kind did you have in mind? I think part of the problem is that the code, beyond java boilerplate, is so small that there are not any units to be tested. It is more or less, process data that would be in the database or not run at all.

Anyway, I am going to work at testing the file idea because it gives you something  for regression testing.

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner , thanks for the detailed report. I believe the philosophy of the unit test would require to use a mock opensearch/elasticsearch interface which would return hard-coded results expected from the database in the cases of your tests. In theory, unit tests do not need external components to work and aims at strictly test the code of the tested component without impact from connected components (e.g. elasticsearch).

In this case, the unit test may sound over-kill to you but we also have to think from the perspective of another developer who would need to understand each significantly complex function that you wrote and make sure he/she does not break it.

**Comment by al-niessner** [comment]
> Hi @al-niessner , thanks for the detailed report. I believe the philosophy of the unit test would require to use a mock opensearch/elasticsearch interface which would return hard-coded results expected from the database in the cases of your tests. In theory, unit tests do not need external components to work and aims at strictly test the code of the tested component without impact from connected components (e.g. elasticsearch).
> 
> In this case, the unit test may sound over-kill to you but we also have to think from the perspective of another developer who would need to understand each significantly complex function that you wrote and make sure he/she does not break it.

Yes, this is the file based approach and am working on it now. It seems to be working well enough despite some number of files having to be added to validate repo. However it has this already for its extensive cucumber tests so not really a diversion from validates norm.
