### ISSUE TITLE
As a user, I want to throw a WARNING when a product's schematron version does not match the schema version

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#628]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data User, Archivist

### 💪 Motivation

...so that I can ensure the versions of the schematron and schema are the same.

### 📖 Additional Details

Unfortunately, the only way we can really check this is via the filenames in the `xml-model` element and `schemaLocation`, but it is better than nothing.

### Acceptance Criteria

**Given** a product label with a v1H00 schematron and a v1J00 schema
**When I perform** validation of the product
**Then I expect** a WARNING to be thrown for a version mismatch

**Given** a product label with a v1H00 schematron and a v1H00 schema
**When I perform** validation of the product
**Then I expect** the product to validate successfully

(probably only need a test case for the first acceptance criteria)

### ⚙️ Engineering Details

Test data: 
[mp2_flat_20061109.xml.txt](https://github.com/NASA-PDS/validate/files/11253671/mp2_flat_20061109.xml.txt)

**Comment by al-niessner** [comment]
@jordanpadams 

A test set with a successful and failure condition would be helpful. Grepped the code for the versions you listed and found nothing. Not sure where these version numbers exist and how they are used. Therefore, need a good example or test case.

**Comment by jordanpadams** [comment]
@al-niessner test data added. note `schemaLocation` references `https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1J00.xsd` and  `xml-model` references `https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1I00.sch`

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

Worked through the schema loading and schematron loading. Unfortunately the schema is loaded via 3rd party library for validation reasons and the file names are ignored by the label check. The schematron are kept in a Java Map within the label check. It means after schema is loaded, validation takes place, and the schematron is run then the schema filenames will have to be loaded again and compared against the schematron Map. It is a little clunky because it means reading the XML one more time to extract the schema names.
