### ISSUE TITLE
validate.addContextProducts does not read a directory of context objects

### ISSUE THREAD

**Issue by tbarnes4** [NASA-PDS-Incubator/validate#648]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I use the --add-context-products on the command line or validate.addContextProducts in the configuration file and point to a directory that contains several context objects (*.xml), I get the error "Invalid JSON File: Verify format and values match that in Non RegisteredProducts File ...".  

### 🕵️ Expected behavior

The help message of validate says that we can specify a JSON file or a directory of files.  Does this mean in order to validate against unregistered context objects we need to create a JSON file or point to a directory of JSON files?  I would hope or expect I can point to a context object and it would validate.

### 📜 To Reproduce

1. Have a directory, [source_context_directory] that contains context object files (*.xml).
2. Run command: % validate [example_data_product].xml --add-context-products [source_context_directory]

### 🖥 Environment Info

- Version of this software: validate Version 3.2.0
- Operating System: macOS Monterey (Version 12.6)
...

### 📚 Version of Software Used

% validate -V

gov.nasa.pds:validate
Version 3.2.0
Release Date: 2023-04-14 00:53:23

Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@tbarnes4 this flag supposed to point to a JSON file that should look something like this:

https://github.com/NASA-PDS/validate/blob/main/src/main/resources/util/registered_context_products.json 

Creating this file is pretty straightforward, especially for a bundle's worth of context products. Note: This should only be used for in-development bundles. All context products should be registered with EN (Richard Chen), prior to release.

If you would like to have a new requirement for reading a directory of context products, feel free to resubmit as a new requirement. However, since there is a workaround in place for this, and this is for in-development bundles only, this will most likely be low on our priority list. Let us know if you have more questions.

**Comment by jordanpadams** [comment]
closing as invalid
