### ISSUE TITLE
validate does not validate a collection if collection.xml pointed to

### ISSUE THREAD

**Issue by tbarnes4** [NASA-PDS-Incubator/validate#649]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I run validate on a collection, specify the rule, and point to the collection.xml file, it will produce a report specifying only: 

>   FAIL: gov.nasa.pds.validate.ValidateLauncher
      ERROR  [error.execution.no_products_found]   No Products found during Validate execution. Verify arguments, paths, and expected label extension. See documentation for details.

Ex: % validate [path]/collection.xml -R pds4.collection;

But if I point to the root directory of the collection, validate will work as expected.

Ex: % validate [path]/ -R pds4.collection;

I get the same result if these are specified in a configuration file with validate.rule = pds4.collection and specify a validate.target or do so from the command line.

### 🕵️ Expected behavior

I expected validate to validate a pds4 collection and not tell me it could not find any products.  This is the behavior I get when doing this for a bundle whether I point to the bundle*.xml file or the root directory of the bundle.

### 📜 To Reproduce

1. Locate a complete collection and identify the [full_path] to the collection*.xml file.
2. Run the command: % validate [full_path/collection*.xml] -R pds4.collection;
3. Read report.

### 🖥 Environment Info

Version of this software: validate Version 3.2.0
Operating System: macOS Monterey (Version 12.6)

### 📚 Version of Software Used

I used tested this on versions 3.2.0 and 3.1.1.

% [path]/validate-3.2.0/bin/validate -V

gov.nasa.pds:validate
Version 3.2.0
Release Date: 2023-04-14 00:53:23

Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.

% [path]/validate-3.1.1/bin/validate -V

gov.nasa.pds:validate
Version 3.1.1
Release Date: 2023-01-03 23:08:19

Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.

### 🦄 Related requirements

🦄 #xyz

**Comment by al-niessner** [comment]
@jordanpadams 

Want to allow specific bundles and collections or continue to require a directory?

The start of the problem is here:
https://github.com/NASA-PDS/validate/blob/d38e2983e77614f726202bdbab2040a9b451186d/src/main/java/gov/nasa/pds/tools/validate/rule/pds4/CollectionValidationRule.java#L36-L38

It is a small class whose sole responsibility is to make sure that when `-R pds4.collection` is given that the target(s) are directories. You will find that bundles are identical with a similarly simple class with same sole responsibility.

It can be fixed but will probably break a lot after it and the bundle/collection probably use the directory only so that it can verify the aggregation that the bundle/collection hold. It could be assumed that aggregate elements are below the bundle/collection but it would break things where the directory structure is more less like root/aggs/collection.xml and root/labels/foo.xml where collection references labels/foo.xml -- the validate is `-R pds4.collection -t /some/path/root` would work but `-R pds4.collection -t /some/path/root/aggs/collection.xml` would fail because it cannot find labes/foo.xml. For the command to work, the directory structure would have to be root/collection.xml and root/labels/foo.xml where collection still references labels/foo.xml and the command `-R pds4.collection -t /some/path/root/collection.xml`.

Do you want to move forward with all the new restrictions and potentially more as more and more bugs are uncovered or just say bundle/collection must use `-t {adir}` as it is now?

**Comment by tbarnes4** [comment]
@al-niessner @jordanpadams 

Question:  Why does `-R pds4.bundle -t /some/path/bundle.xml` work?  I raised the issues seeing that pointing to the collection.xml file does not work the same way as for the bundle.xml.  In the latter case, validate appears to assume that the root directory is the directory that bundle.xml lives.  I would hope that this would be the same for collection.xml.

**Comment by al-niessner** [comment]
@tbarnes4 

Interesting. Just ran it with the debugger and it behaves as expected, like collections. When I use `-R pds4.bundle -t bundle.xml` I get this error:
```
ERROR  [error.execution.no_products_found]   No Products found during Validate execution. Verify arguments, paths, and expected label extension. See documentation for details.
```

from here:
https://github.com/NASA-PDS/validate/blob/d38e2983e77614f726202bdbab2040a9b451186d/src/main/java/gov/nasa/pds/tools/validate/rule/pds4/BundleValidationRule.java#L37

via here:
https://github.com/NASA-PDS/validate/blob/d38e2983e77614f726202bdbab2040a9b451186d/src/main/java/gov/nasa/pds/tools/label/LocationValidator.java#L264



Cannot explain why you are seeing something different. Blame says the check at L264 has been there for 4+ years. The other code is also 4+ years old.

**Comment by al-niessner** [comment]
@tbarnes4 

My mistake. Had to give it a bundle and not a collection. The bundle erases the actual filename and uses just the directory and does a full bundle check. It means it would check other bundles it finds in that directory tree. Not really what you asked of it. I guess that needs fixin too.

**Comment by al-niessner** [comment]
Fixing this alters the fix for #238 as it does not turn the bundle into a directory.

**Comment by tbarnes4** [comment]
@al-niessner 

My two cents.... I think it is better that if you point to a bundle or collection file name, than it only validates that bundle or collection product file, and then their associated products only if the proper rule is declared (-R pds4.collection or pds4.bundle).  If you specify a directory, then it should just run whatever rule is being declared (or defaulted to if none is declared).  There are times we only want to check the individual product verse the whole collection or bundle, though I usually only do the whole collection or bundle myself.

**Comment by al-niessner** [comment]
@tbarnes4 

Yes, that is what we are working towards.
