### ISSUE TITLE
Upgrade to Saxon 12.x

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#707]
## 💡 Description

[Saxon 9 appears to be EOL](https://github.com/Saxonica/Saxon-HE#current-releases), so let's upgrade Saxon to the latest version. Per this [branch test from dependabot PR](https://github.com/NASA-PDS/validate/actions/runs/6355118777), there are some backwards incompatible updates we will need to address.

Changes can be made directly to this dependabot branch: https://github.com/NASA-PDS/validate/tree/dependabot/maven/net.sf.saxon-Saxon-HE-12.3

- [x] Update for initial merge here: https://github.com/NASA-PDS/validate/pull/701
- [ ] Update next to catch erroneous messages hitting stdout: https://github.com/NASA-PDS/validate/pull/701#issuecomment-1749265874

**Comment by jordanpadams** [comment]
@al-niessner this is next up after the error message update

**Comment by jordanpadams** [comment]
- [X] Initial merge complete here: https://github.com/NASA-PDS/validate/pull/701
- [ ] Update next to catch erroneous messages hitting stdout: https://github.com/NASA-PDS/validate/pull/701#issuecomment-1749265874

**Comment by jordanpadams** [comment]
Status: Merged #701. Working on cleaning up std out messages

**Comment by al-niessner** [comment]
@jordanpadams 

Please tell me the intent of these lines:
https://github.com/NASA-PDS/validate/blob/15f58ea16e1d34e12c091bb62941e516165e504c/src/main/java/gov/nasa/pds/tools/validate/rule/RegisterTargets.java#L52-L54

I know what they do and this is a major source of reading all files as possible labels rather than doing just xml and lbx or whatever. Since we convert labels to targets in validate, the naming makes sense. I just do not understand caption in terms of context (it is PDS4 Bundle in the test) and why when it is not PDS4 Directory we want to look at all files. Hence I need the intent to know how to appropriately fixes these lines.

**Comment by al-niessner** [comment]
Side note, saxon 12.3 will not silenced. Tried several hooks for errors that saxon provides and non are called for the errors we are seeing related to prolog messages.

**Comment by jordanpadams** [comment]
tabling this from current sprint and foreseeable future. See comments on #726 for details

**Comment by al-niessner** [comment]
@jordanpadams 

Got response back from SAXON. Fixed correctly.
