### ISSUE TITLE
Validate is expecting uppercase context references (context_ref_case_mismatch)

### ISSUE THREAD

**Issue by mace-space** [NASA-PDS-Incubator/validate#724]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I ran validate on a bundle with verbosity flag of 1 (severity level = INFO), it reported `info.label.context_ref_case_mismatch`, for example:

 `Context reference name case mismatch. Value: 'Cassini-Huygens' Expected one of: '[CASSINI-HUYGENS]'
 INFO  [info.label.context_ref_found]  ...Context product found: 'urn:nasa:pds:context:instrument_host:spacecraft.co'`
`Context reference name mismatch. Value: 'Cassini Orbiter Ultraviolet Imaging Spectrograph' Expected one of: '[ULTRAVIOLET IMAGING SPECTROGRAPH]'`
`INFO  [info.label.context_ref_case_mismatch]  ...Context reference name case mismatch. Value: 'Saturn Rings' Expected one of: '[SATURN RINGS]'`
`INFO  [info.label.context_ref_case_mismatch]  ... Context reference type case mismatch. Value: 'Ring' Expected one of: '[RING]'`

### 🕵️ Expected behavior

I don't think context references should use uppercase as Validate is noting, but rather should be using title case (as the labels are currently).

### 📜 To Reproduce

validate bundle_name -R pds4.bundle -v 1 -r bundle_validate.log

### 📚 Version of Software Used

Validate v3.1.1

### 🦄 Related requirements

🦄 #xyz

**Comment by al-niessner** [comment]
@jordanpadams @mace-space 

Validate does not actually have a defined case for any of these names. The case comparison is done against a file that it was generated from grabbing certain documents registered with PDS - Context Products specifically. Validate only compares the case from these Context Products to what is in the given label(s).

It may be that this file needs to be regenerated because some case changes have been made. However a quick look says that most of the names and types are yelling at you but a few are not. Examples:
```
               "name": [
                    "COSMIC RAY SUBSYSTEM"
               ],
               "type": [
                    "PARTICLE DETECTOR"
               ],
```
vs
```
               "name": [
                    "UWO Meteor Radar Complex"
               ],
               "type": [
                    "Observatory"
               ],
```

There is a tool in validate that allows you to generate this file if you think it needs to regenerated. Please see the documentation for building the registered_context_products.json file and how to have validate use the one you built.

Side note: show the two examples was meant to illustrate that the tool does not change the case to yell at you.

**Comment by jordanpadams** [comment]
@al-niessner can we just update the code to ignore case in its comparison?

**Comment by al-niessner** [comment]
@jordanpadams 

Technically validate is doing a case-insensitive test. It is how it determines case mismatch. It then emits an INFO message (read error given by user). Do you not want the INFO? Is there a reason why the INFO is so offensive since it does not cause validate to fail the label?

I spent 5 minutes looking at our closed tickets because I remember being over this ground already but did not find it. It was 4 years ago that it went from warning to info which is before my time.

**Comment by jordanpadams** [comment]
@al-niessner To clarify, I am recommending we just remove the case-insensitive test entirely.

**Comment by jordanpadams** [comment]
@mace-space Oops! Just saw this was already fixed: https://github.com/NASA-PDS/validate/issues/631
