### ISSUE TITLE
Review Handling of Special Constants, Field Formats, and High Priority Bug Fixes

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#832]
### 💡 Description

It appears we have some improvements needed for handling of special constants and field formats according to the standards and what errors/warnings/info messages should be output to to the user.

### 👶 Child Tasks

- #849
- #854 
- #873
- #874
- #880
- #831 
- #817 
- #816 
- #837
- #903

**Comment by msbentley** [comment]
Hi @jordanpadams @jmafi Special_Constants is on my list of "things to raise with DDWG" so before we make too many changes to validate, I think a discussion is needed here, in particular wrt how we handle IEEE754 data + special constants...

**Comment by al-niessner** [comment]
@jordanpadams 

If I understand #816 and #817 correctly, then [check_format()](https://github.com/NASA-PDS/validate/blob/3d84b0ed6f7ccec90e472d295e774de11607fdf5/src/main/java/gov/nasa/pds/tools/validate/content/table/FieldValueValidator.java#L771) needs to change its error if field or validation format and all errors in this function need to have error/warning counterparts. Leave the message the same otherwise I hope. Correct?

**Comment by jordanpadams** [comment]
@al-niessner correct. right now we are treating [all precision the same](https://github.com/NASA-PDS/validate/blob/3d84b0ed6f7ccec90e472d295e774de11607fdf5/src/main/java/gov/nasa/pds/tools/validate/content/table/FieldValueValidator.java#L839). We need to know not just that there is a precision value, but whether or not it is exact precision (validation_format) vs. max precision (field_format). So  I think the [current check here](https://github.com/NASA-PDS/validate/blob/3d84b0ed6f7ccec90e472d295e774de11607fdf5/src/main/java/gov/nasa/pds/tools/validate/content/table/FieldValueValidator.java#L850) should be a warning for `field_format`, but we need an additional check for not equal for `validation_format`

**Comment by jordanpadams** [comment]
All sub-tasks completed. Closing out
