### ISSUE TITLE
Null filename error after OOM

### ISSUE THREAD

**Issue by rgdeen** [NASA-PDS-Incubator/validate#913]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

I was validating MSAM2 a sol at a time (so validate is running with an entire directory of several hundred products).  On several sols, I got an out of memory error as it tried to validate >> 2GB mosaics.  Not a problem, I'll rerun with more memory.  However, later in the same run it would often (but not always) do this:

```
  PASS: file:/mnt/pdsdata/scratch/rgd/msam2/annex_ehlmann_caltech_msl_msam2/data/sol/00580/opgs/rdr/mcam/MRF_448992322DFFAS0300740MCAM02407D1.xml
        6189 product validation(s) completed

  FAIL: file:/mnt/pdsdata/scratch/rgd/msam2/annex_ehlmann_caltech_msl_msam2/data/sol/00580/opgs/rdr/mcam/
      ERROR  [error.validation.internal_error]   Uncaught exception while validating: null

  PASS: file:/mnt/pdsdata/scratch/rgd/msam2/annex_ehlmann_caltech_msl_msam2/data/sol/00580/opgs/rdr/mcam/MRF_448991045SRD_S0300740MCAM02407D1.xml
        6190 product validation(s) completed

  FAIL: file:/mnt/pdsdata/scratch/rgd/msam2/annex_ehlmann_caltech_msl_msam2/data/sol/00580/opgs/rdr/mesh/
      ERROR  [error.validation.internal_error]   Uncaught exception while validating: null
```

Note the empty filename on the FAIL message.

The prior OOM looked like this:
```
  FAIL: file:/mnt/pdsdata/scratch/rgd/msam2/annex_ehlmann_caltech_msl_msam2/data/sol/00580/opgs/rdr/mcam/MLF_448990275MDSAS0300740MCAM02407D1.xml
    Begin Content Validation: file:/mnt/pdsdata/scratch/rgd/msam2/annex_ehlmann_caltech_msl_msam2/data/sol/00580/opgs/rdr/mcam/MLF_448990275MDSAS0300740MCAM02407D1.IMG
      FATAL_ERROR  [error.validation.out_of_memory]   array 1: Out of memory error occurred while processing array. Please adjust the JVM Heap Space settings and try again.
    End Content Validation: file:/mnt/pdsdata/scratch/rgd/msam2/annex_ehlmann_caltech_msl_msam2/data/sol/00580/opgs/rdr/mcam/MLF_448990275MDSAS0300740MCAM02407D1.IMG
        6187 product validation(s) completed
```

### 🕵️ Expected behavior

The null filename was surprising.  I suspect something got messed up internally with the OOM but Jordan suggested I write it up as a bug anyway.

### 📜 To Reproduce

Probably:

Validate an entire directory of images.  Make sure some of them are huge to force an OOM error (maybe even reduce the java heap size).  It's not 100%.  On a run of about 200 sols, 14 failed with OOM.  Of those, 7 had the null error.

### 🖥 Environment Info

Validate 3.4.1

[rgd@pdsimg-int1 msam2]$ uname -a
Linux pdsimg-int1 3.10.0-1160.76.1.el7.x86_64 #1 SMP Tue Jul 26 14:15:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### 📚 Version of Software Used

3.4.1

### 🦄 Related requirements

🦄 #xyz

**Comment by al-niessner** [comment]
If I am reading this right, the null errors only occurred when there was an OOM error. However there were OOM errors that did not generate the null error.

If my reading is correct, then the null errors sometimes is not a surprise. It seems the current sagely advice for OOM errors on the net is the same as the old sagely advice: Stop the program and fix the memory or code. The OOM indicates that it could not create some object in heap, stack, somewhere - oracle has a good details on the dozen ways it can really happen despite the most common and easy answer being heap. Independent of the exact cause, the result is the same in that data elements that you expected to be created were not. No surprise that sometimes it is the var that is to be printed out. Strings are vary likely since there are no duplicates in Java so turning the URL into a filename for you to see requires heap and stack.

All that said, I have no idea why @jordanpadams suggested that you log it as a bug. Nor is there any good way to "fix" the null output when generating the string you want to read is the null from the OOM error. Also, once the OOM is caught there is not way to know that the GC has run to alleviate the OOM and the string simply cannot be generated.

@jordanpadams what did you have in mind for this? Really, processing after an OOM is super terrible idea/approach. Schematron are stored statically (GC cannot touch them) so if that was did not get created then you will get really odd null pointer exceptions later.

@rgdeen is it possible to use find - something like `find . -name \*.xml -exec validate.sh -t {} \;` - to process even smaller chunks to avoid the OOM? Probably would make s giant mess of recombining the logs to see what if anything failed though.

**Comment by rgdeen** [comment]
honestly I'm not sure either.  ;-)

The OOM is occurring on super huge files (prob around 10GB) and should be avoidable by upping the java heap space.

**Comment by al-niessner** [comment]
@jordanpadams @rgdeen 

The only suggestion I would have is to not load the images but check them for compatibility or something instead. Should be able to if a file is really a JPG and that it can be read by a JPG reader without actually loading the file for instance. validate does not display the images it loads so loading it must be the fast and easy way to verify it is of the type it says it is and is readable as that type.

**Comment by rgdeen** [comment]
it's not a jpeg it's a vicar file, which is an Array_2D_Image type.  Anyway, I'm okay with just upping the heap size when needed.  I guess the thing to look into is whether you are loading the entire image (array) to validate it or if it could be loaded in chunks and discarded.

**Comment by jordanpadams** [comment]
@rgdeen it is being loaded in chunks. depending upon the system you are running this on and/or the version of java will also dictate how fast garbage collection is able to gain back memory. this may also be something that has been improved since we fixed a memory leak in the latest version of validate (3.5.1)
